### ISSUE TITLE
CAN'T INSTALL

### ISSUE THREAD

**Issue by francop-eb** [atombender/homebrew-ktail#1]
glide install --strip-vendor

[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching cloud.google.com/go
[INFO]	--> Fetching github.com/googleapis/gnostic
[INFO]	--> Fetching github.com/mattn/go-colorable
[INFO]	--> Fetching github.com/howeyc/gopass
[INFO]	--> Fetching github.com/gogo/protobuf
[INFO]	--> Fetching github.com/jpillora/backoff
[INFO]	--> Fetching github.com/golang/glog
[INFO]	--> Fetching github.com/fatih/color
[INFO]	--> Fetching golang.org/x/net
[INFO]	--> Fetching github.com/json-iterator/go
[INFO]	--> Fetching github.com/ghodss/yaml
[INFO]	--> Fetching golang.org/x/crypto
[INFO]	--> Fetching github.com/spf13/pflag
[INFO]	--> Fetching github.com/golang/protobuf
[INFO]	--> Fetching github.com/hashicorp/golang-lru
[INFO]	--> Fetching github.com/davecgh/go-spew
[INFO]	--> Fetching github.com/imdario/mergo
[INFO]	--> Fetching github.com/coreos/go-oidc
[INFO]	--> Fetching github.com/google/gofuzz
[INFO]	--> Fetching github.com/mattn/go-isatty
[INFO]	--> Fetching golang.org/x/oauth2
[INFO]	--> Fetching golang.org/x/sys
[INFO]	--> Fetching golang.org/x/time
[INFO]	--> Fetching golang.org/x/text
[INFO]	--> Fetching google.golang.org/appengine
[INFO]	--> Fetching gopkg.in/inf.v0
[INFO]	--> Fetching gopkg.in/yaml.v2
[INFO]	--> Fetching k8s.io/api
[INFO]	--> Fetching k8s.io/apimachinery
[INFO]	--> Fetching k8s.io/client-go
[INFO]	Setting references.
[INFO]	--> Setting version for github.com/mattn/go-colorable to 5411d3eea5978e6cdc258b30de592b60df6aba96.
[INFO]	--> Setting version for github.com/howeyc/gopass to bf9dde6d0d2c004a008c27aaee91170c786f6db8.
[INFO]	--> Setting version for github.com/golang/protobuf to 1643683e1b54a9e88ad26d98f81400c8c9d9f4f9.
[INFO]	--> Setting version for github.com/jpillora/backoff to 8eab2debe79d12b7bd3d10653910df25fa9552ba.
[INFO]	--> Setting version for github.com/json-iterator/go to 13f86432b882000a51c6e610c620974462691a97.
[INFO]	--> Setting version for github.com/ghodss/yaml to 73d445a93680fa1a78ae23a5839bad48f32ba1ee.
[INFO]	--> Setting version for github.com/coreos/go-oidc to 8ae1da518bd4d9d5a5909090a184af30f336436d.
[INFO]	--> Setting version for github.com/hashicorp/golang-lru to a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4.
[INFO]	--> Setting version for github.com/spf13/pflag to 3ebe029320b2676d667ae88da602a5f854788a8a.
[INFO]	--> Setting version for github.com/mattn/go-isatty to 57fdcb988a5c543893cc61bce354a6e24ab70022.
[INFO]	--> Setting version for github.com/fatih/color to 5b77d2a35fb0ede96d138fc9a99f5c9b6aef11b4.
[INFO]	--> Setting version for github.com/googleapis/gnostic to 0c5108395e2debce0d731cf0287ddf7242066aba.
[INFO]	--> Setting version for github.com/davecgh/go-spew to 782f4967f2dc4564575ca782fe2d04090b5faca8.
[INFO]	--> Setting version for github.com/imdario/mergo to 6633656539c1639d9d78127b7d47c622b5d7b6dc.
[INFO]	--> Setting version for github.com/google/gofuzz to 44d81051d367757e1c7c6a5a86423ece9afcf63c.
[INFO]	--> Setting version for github.com/golang/glog to 44145f04b68cf362d9c4df2182967c2275eaefed.
[INFO]	--> Setting version for github.com/gogo/protobuf to c0656edd0d9eab7c66d1eb0c568f9039345796f7.
[INFO]	--> Setting version for golang.org/x/crypto to 81e90905daefcd6fd217b62423c0908922eadb30.
[INFO]	--> Setting version for golang.org/x/net to 1c05540f6879653db88113bc4a2b70aec4bd491f.
[INFO]	--> Setting version for cloud.google.com/go to 3b1ae45394a234c385be014e9a488f2bb6eef821.
[INFO]	--> Setting version for golang.org/x/oauth2 to a6bd8cefa1811bd24b86f8902872e4e8225f74c4.
[INFO]	--> Setting version for google.golang.org/appengine to b1f26356af11148e710935ed1ac8a7f5702c7612.
[INFO]	--> Setting version for k8s.io/api to 73d903622b7391f3312dcbac6483fed484e185f8.
[INFO]	--> Setting version for k8s.io/client-go to 23781f4d6632d88e869066eaebb743857aa1ef9b.
[INFO]	--> Setting version for k8s.io/apimachinery to 302974c03f7e50f16561ba237db776ab93594ef6.
[INFO]	--> Setting version for golang.org/x/time to f51c12702a4d776e4c1fa9b0fabab841babae631.
[INFO]	--> Setting version for golang.org/x/text to b19bf474d317b857955b12035d2c5acb57ce8b01.
[INFO]	--> Setting version for golang.org/x/sys to 07c182904dbd53199946ba614a412c61d3c548f5.
[INFO]	--> Setting version for gopkg.in/inf.v0 to 3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4.
[INFO]	--> Setting version for gopkg.in/yaml.v2 to 670d4cfef0544295bc27a114dbac37980d83185a.
[INFO]	Exporting resolved dependencies...
[INFO]	--> Exporting github.com/ghodss/yaml
[INFO]	--> Exporting github.com/davecgh/go-spew
[INFO]	--> Exporting github.com/coreos/go-oidc
[INFO]	--> Exporting github.com/gogo/protobuf
[INFO]	--> Exporting github.com/fatih/color
[INFO]	--> Exporting github.com/golang/protobuf
[INFO]	--> Exporting github.com/google/gofuzz
[INFO]	--> Exporting github.com/golang/glog
[INFO]	--> Exporting github.com/imdario/mergo
[INFO]	--> Exporting github.com/googleapis/gnostic
[INFO]	--> Exporting github.com/howeyc/gopass
[INFO]	--> Exporting github.com/jpillora/backoff
[INFO]	--> Exporting github.com/hashicorp/golang-lru
[INFO]	--> Exporting github.com/mattn/go-colorable
[INFO]	--> Exporting github.com/json-iterator/go
[INFO]	--> Exporting github.com/mattn/go-isatty
[INFO]	--> Exporting github.com/spf13/pflag
[INFO]	--> Exporting golang.org/x/crypto
[INFO]	--> Exporting golang.org/x/net
[INFO]	--> Exporting cloud.google.com/go
[INFO]	--> Exporting golang.org/x/oauth2
[INFO]	--> Exporting golang.org/x/text
[INFO]	--> Exporting golang.org/x/sys
[INFO]	--> Exporting google.golang.org/appengine
[INFO]	--> Exporting k8s.io/apimachinery
[INFO]	--> Exporting golang.org/x/time
[INFO]	--> Exporting k8s.io/api
[INFO]	--> Exporting gopkg.in/yaml.v2
[INFO]	--> Exporting gopkg.in/inf.v0
[INFO]	--> Exporting k8s.io/client-go
[INFO]	Replacing existing vendor dependencies
[INFO]	Removing nested vendor and Godeps/_workspace directories...
[INFO]	Removing: /private/tmp/ktail-20180926-8548-72xrkv/src/github.com/atombender/ktail/vendor/github.com/fatih/color/vendor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x131f192]

goroutine 1 [running]:
github.com/Masterminds/glide/path.StripVendor.func1(0xc000755600, 0x77, 0x0, 0x0, 0x1540360, 0xc000193500, 0x0, 0x0)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/path/strip.go:28 +0x42
path/filepath.walk(0xc00013e850, 0x6c, 0x1547640, 0xc0007489c0, 0xc0003baa20, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:378 +0x21f
path/filepath.walk(0xc00013e000, 0x65, 0x1547640, 0xc000748270, 0xc0003baa20, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
path/filepath.walk(0xc00009e1e0, 0x5f, 0x1547640, 0xc0007481a0, 0xc0003baa20, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
path/filepath.walk(0xc0003642a0, 0x59, 0x1547640, 0xc000749450, 0xc0003baa20, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
path/filepath.walk(0xc000273a90, 0x4e, 0x1547640, 0xc0002d7040, 0xc0003baa20, 0x0, 0x20)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:382 +0x2fe
path/filepath.Walk(0xc000273a90, 0x4e, 0xc0003baa20, 0xc0002d6f70, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/path/filepath/path.go:404 +0x105
github.com/Masterminds/glide/path.StripVendor(0x14d5ddf, 0x3b)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/path/strip.go:22 +0x106
github.com/Masterminds/glide/action.Install(0xc0001ee580, 0x14c1501)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/action/install.go:62 +0x351
main.commands.func12(0xc0001269a0, 0x0, 0xc0001269a0)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/glide.go:510 +0x2b5
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.HandleAction(0x1438080, 0x14e03f0, 0xc0001269a0, 0xc0000cb700, 0x0)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:490 +0xc8
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x14bf842, 0x7, 0x14bde6b, 0x1, 0x0, 0x0, 0x0, 0x14cb14f, 0x20, 0x0, ...)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:210 +0x990
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc0000b7380, 0xc0000ac090, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:255 +0x687
main.main()
	/private/tmp/glide-20180907-39878-1g2n9m3/glide-0.13.1/src/github.com/Masterminds/glide/glide.go:104 +0x556

HOMEBREW_VERSION: 1.7.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: f239b7a62790cfb4f33bda9aab7597d43f1b1e3b
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a2aa4aecd954223776009a42316fb95d09318716
Core tap last commit: 20 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/francop/Library/Caches/Homebrew
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 9.4.1
XQuartz: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
ACLOCAL_PATH: /usr/local/share/aclocal

**Comment by atombender** [comment]
Hi, can you try now?
